name: Build Blender Extension

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Blender
      run: | 
        wget https://download.blender.org/release/Blender4.2/blender-4.2.4-linux-x64.tar.xz -O blender.tar.xz
        mkdir blender
        tar -xvf blender.tar.xz -C blender --strip-components=1
    - name: Move files
      run: mkdir extension && mv __init__.py blender_manifest.toml node_runner_*.py extension/
        
    - name: Build Blender Extension
      run: cd extension && ../blender/blender --command extension build
    - name: Move zip file
      run: mkdir build_output && mv extension/node_runner-*.zip build_output
    - name: Archive Build
      uses: actions/upload-artifact@v4
      with: 
        name: blender-extension-build
        path: build_output/


